Logging
Manchester-Central/2023-Charged-Up pull request #23
Opened 2023-01-24 23:20 UTC by NinjaBuilderPro

Adds logs to the robot with information about the robot.

2023-01-24 23:23 UTC, averwhy approved these changes
LGTM 👍

2023-01-24 23:28 UTC, averwhy requested changes

2023-01-24 23:28 UTC, averwhy commented on src/main/java/frc/robot/Robot.java
> +   */
Unnecessary. Remove

2023-01-24 23:31 UTC, AratosUnderscore approved these changes

2023-01-24 23:34 UTC, averwhy commented on src/main/java/frc/robot/Robot.java
> +   */
![image](https://user-images.githubusercontent.com/43783082/214444539-16d8e513-1901-4a8a-a529-43efb2ded50e.png)

2023-01-24 23:37 UTC, averwhy approved these changes

2023-01-24 23:37 UTC, averwhy commented
LGTM 
![image](https://user-images.githubusercontent.com/43783082/214445010-8a448fcf-2de2-4049-8d95-a308778fab4b.png)

2023-01-24 23:38 UTC, AratosUnderscore approved these changes
poggers

2023-01-24 23:39 UTC, merged

2023-01-25 23:01 UTC, jnallard commented
Fixed #11