Speed desaturation
Manchester-Central/2023-Charged-Up pull request #56
Opened 2023-02-11 18:50 UTC by Kenneth-Olibrice

2023-02-11 18:51 UTC, averwhy requested changes, later dismissed

2023-02-11 18:51 UTC, averwhy commented on src/main/java/frc/robot/subsystems/SwerveDrive.java
> +    ChassisSpeeds currentSpeed = m_kinematics.toChassisSpeeds(getModuleStates()); // TODO TEST THIS
you have a TODO in your code

2023-02-11 19:10 UTC, averwhy reviewed
much better

2023-02-15 00:09 UTC, averwhy reviewed
not working atm afaik, made draft until we test again 👍

2023-03-23 04:06 UTC, jnallard commented on src/main/java/frc/robot/RobotContainer.java
> +    m_tester.x().whileTrue(new DriveToTarget(m_swerveDrive, new Pose2d(xStart, yStart + 1, Rotation2d.fromDegrees(180)), Constants.DriveToTargetTolerance));
Added this to this branch as we will test this with the desaturation changes tomorrow

2023-03-24 00:34 UTC, jnallard approved these changes

2023-03-24 00:35 UTC, tri-vu-12 approved these changes
Looked over as a team!

2023-03-24 00:35 UTC, merged